### ISSUE TITLE
Add symlink to cpp?

### ISSUE THREAD

**Issue by sogaiu** [andrewchambers/hpkgs#80]
Some of the xorg-related packages would be happier being able to invoke cpp.

Perhaps an appropriate link in these two places:

https://github.com/andrewchambers/hpkgs/blob/master/bootstrap.sh#L85_L98
https://github.com/andrewchambers/hpkgs/blob/master/core.hpkg#L291_L304

makes sense?

**Comment by andrewchambers** [comment]
Makes sense to me. Note gcc normally makes these links itself, I think it doesn't because it thinks we are cross compiling. We might need to address the root cause.

**Comment by sogaiu** [comment]
I looked into it a bit but so far haven't had much luck.

If you have some leads, I'm willing to look into it further.

**Comment by sogaiu** [comment]
On the subject of symlinks, found this:

> musl’s dynamic linker comes with ldd functionality built in. Just create a symlink from ld-musl-$ARCH.so to /bin/ldd. If the dynamic linker was started as “ldd”, it will detect that and print the appropriate DSO information.

https://wiki.musl-libc.org/faq.html

Would it be worth having this specially named link?

**Comment by andrewchambers** [comment]
yes I think so, looks good!

**Comment by sogaiu** [comment]
I think we can close this because https://github.com/andrewchambers/hpkgs/commit/940d999e1a684cb1c85632ff418c3a580664eafa appears to address it.
