### ISSUE TITLE
--enable-new-dtags should be the default for our ld

### ISSUE THREAD

**Issue by andrewchambers** [andrewchambers/hpkgs#88]
We have no backwards compatibility to maintain, we can work out how to make this the default.

**Comment by andrewchambers** [comment]
Also for our clang/lld if needed.

**Comment by sogaiu** [comment]
Hopefully there are no insurmountable adverse consequences -- I suppose it's still worth having some sort of check on the final products.

**Comment by andrewchambers** [comment]
Usually when they add a flag such as --enable-new ... it is because its a migration path from legacy behavior.

I read Gentoo enables this by default from a comment, but we need to verify.

**Comment by sogaiu** [comment]
Here is some related discussion: https://web.archive.org/web/20160101182307/http://comments.gmane.org/gmane.comp.gnu.binutils/57379

**Comment by sogaiu** [comment]
May be this can be closed because of: https://github.com/andrewchambers/hpkgs/commit/e854b835dd170680afcd84d80efe80f46bf7c8e6 ?
